import { Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "./components/NavBar";
import { WorkoutStoreProvider } from "./components/WorkoutStore";
import { inter } from "./fonts";

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${inter.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <WorkoutStoreProvider>
          <NavBar />
          {children}
        </WorkoutStoreProvider>
      </body>
    </html>
  );
}
